-- MySQL Script generated by MySQL Workbench
-- Fri Oct 26 16:32:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema airline
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema airline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airline` DEFAULT CHARACTER SET utf8 ;
USE `airline` ;

-- -----------------------------------------------------
-- Table `airline`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airline`.`clients` (
  `clientID` INT NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(300) NOT NULL,
  `email` VARCHAR(300) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`clientID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airline`.`aircrafts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airline`.`aircrafts` (
  `aircraftID` INT NOT NULL AUTO_INCREMENT,
  `immatriculation` VARCHAR(30) NOT NULL,
  `type` VARCHAR(10) NOT NULL,
  `seats` INT NOT NULL,
  PRIMARY KEY (`aircraftID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airline`.`airports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airline`.`airports` (
  `airportID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `code` VARCHAR(3) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`airportID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airline`.`links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airline`.`links` (
  `linkID` INT NOT NULL AUTO_INCREMENT,
  `departure_airportID` INT NOT NULL,
  `arrival_airportID` INT NOT NULL,
  PRIMARY KEY (`linkID`),
  INDEX `fk_liaisons_airports1_idx` (`departure_airportID` ASC) ,
  INDEX `fk_liaisons_airports2_idx` (`arrival_airportID` ASC) ,
  CONSTRAINT `fk_liaisons_airports1`
    FOREIGN KEY (`departure_airportID`)
    REFERENCES `airline`.`airports` (`airportID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_liaisons_airports2`
    FOREIGN KEY (`arrival_airportID`)
    REFERENCES `airline`.`airports` (`airportID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airline`.`flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airline`.`flights` (
  `flightID` INT NOT NULL AUTO_INCREMENT,
  `date1` DATE NOT NULL,
  `date2` DATE NOT NULL,
  `departure_time` TIME NOT NULL,
  `arrival_time` TIME NOT NULL,
  `aircraftID` INT NOT NULL,
  `linkID` INT NOT NULL,
  PRIMARY KEY (`flightID`),
  INDEX `fk_vols_appareils1_idx` (`aircraftID` ASC) ,
  INDEX `fk_vols_liaisons1_idx` (`linkID` ASC) ,
  CONSTRAINT `fk_vols_appareils1`
    FOREIGN KEY (`aircraftID`)
    REFERENCES `airline`.`aircrafts` (`aircraftID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vols_liaisons1`
    FOREIGN KEY (`linkID`)
    REFERENCES `airline`.`links` (`linkID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airline`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airline`.`employees` (
  `employeeID` INT NOT NULL AUTO_INCREMENT,
  `salary` DECIMAL(9,2) NOT NULL,
  `address` VARCHAR(500) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `flight_hours` DECIMAL(9,2) NOT NULL,
  `social_security_number` INT NOT NULL,
  `roleID` INT NOT NULL,
  PRIMARY KEY (`employeeID`),
   INDEX `fk_role_idx` (`roleID` ASC) ,
  CONSTRAINT `fk_role`
    FOREIGN KEY (`roleID`)
    REFERENCES `airline`.`role` (`roleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airline`.`departures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airline`.`departures` (
  `departureID` INT NOT NULL AUTO_INCREMENT,
  `departure_date` DATE NOT NULL,
  `free_seats` INT NULL,
  `sold_seats` INT NULL,
  `flightID` INT NOT NULL,
  `pilot1ID` INT NOT NULL,
  `pilot2ID` INT NULL,
  `crew_member1ID` INT NOT NULL,
  `crew_member2ID` INT NOT NULL,
  PRIMARY KEY (`departureID`),
  INDEX `fk_departs_vols1_idx` (`flightID` ASC) ,
  INDEX `fk_departs_pilots1_idx` (`pilot1ID` ASC) ,
  INDEX `fk_departs_pilots2_idx` (`pilot2ID` ASC) ,
  INDEX `fk_departs_crew_members1_idx` (`crew_member1ID` ASC) ,
  INDEX `fk_departs_crew_members2_idx` (`crew_member2ID` ASC) ,
  CONSTRAINT `fk_departs_vols1`
    FOREIGN KEY (`flightID`)
    REFERENCES `airline`.`flights` (`flightID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departs_pilots1`
    FOREIGN KEY (`pilot1ID`)
    REFERENCES `airline`.`pilots` (`pilotID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departs_pilots2`
    FOREIGN KEY (`pilot2ID`)
    REFERENCES `airline`.`pilots` (`pilotID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departs_crew_members1`
    FOREIGN KEY (`crew_member1ID`)
    REFERENCES `airline`.`crew_members` (`crew_memberID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departs_crew_members2`
    FOREIGN KEY (`crew_member2ID`)
    REFERENCES `airline`.`crew_members` (`crew_memberID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airline`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airline`.`tickets` (
  `ticketID` INT NOT NULL AUTO_INCREMENT,
  `date_of_issue` DATETIME NOT NULL,
  `price` DECIMAL(9,2) NOT NULL,
  `departs_iddeparts` INT NOT NULL,
  `clients_clientID` INT NOT NULL,
  PRIMARY KEY (`ticketID`),
  INDEX `fk_tickets_departs1_idx` (`departs_iddeparts` ASC) ,
  INDEX `fk_tickets_clients1_idx` (`clients_clientID` ASC) ,
  CONSTRAINT `fk_tickets_departs1`
    FOREIGN KEY (`departs_iddeparts`)
    REFERENCES `airline`.`departures` (`departureID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_clients1`
    FOREIGN KEY (`clients_clientID`)
    REFERENCES `airline`.`clients` (`clientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `airline`.`role` (
  `roleID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  
  PRIMARY KEY (`roleID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
